name: Cache rust dependencies of multiple crates

inputs:
  folder:
    description: Path to the folder containing the crates (without trailing slash)
    required: true
    default: "./programs"
  key:
    description: A unique key prefix for the cache
    required: true
    default: "programs"

runs:
  using: "composite"
  steps:
    - name: Cache all crates dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ${{ inputs.folder }}/target/
          ${{ inputs.folder }}/**/target/
        key: ${{ runner.os }}-${{ inputs.key }}-${{ hashFiles(format('{0}/Cargo.lock, {0}/**/Cargo.lock', inputs.folder)) }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.key }}
